+incdir+../src
../src/eth_clockgen.v
../src/eth_crc.v
../src/eth_fifo.v
../src/eth_maccontrol.v
../src/ethmac_defines.v
../src/eth_macstatus.v
../src/eth_miim.v
../src/eth_outputcontrol.v
../src/eth_random.v
../src/eth_receivecontrol.v
../src/eth_registers.v
../src/eth_register.v
../src/eth_rxaddrcheck.v
../src/eth_rxcounters.v
../src/eth_rxethmac.v
../src/eth_rxstatem.v
../src/eth_shiftreg.v
../src/eth_spram_256x32.v
../src/eth_transmitcontrol.v
../src/eth_txcounters.v
../src/eth_txethmac.v
../src/eth_txstatem.v
../src/eth_wishbone.v
../src/ethmac.v
