+incdir+../../src
../../src/generic_dpram.v
../../src/generic_spram.v
../../src/timescale.v
../../src/vga_clkgen.v
../../src/vga_colproc.v
../../src/vga_csm_pb.v
../../src/vga_cur_cregs.v
../../src/vga_curproc.v
../../src/vga_defines.v
../../src/vga_enh_top.v
../../src/vga_fifo_dc.v
../../src/vga_fifo.v
../../src/vga_pgen.v
../../src/vga_tgen.v
../../src/vga_vtim.v
../../src/vga_wb_master.v
../../src/vga_wb_slave.v
